<a href="https://colab.research.google.com/github/priyanshu742/PythonIntern/blob/main/MissingData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame({
    'A':[1,2,np.nan],
    'B':[5,np.nan,np.nan],
    'C':[1,2,3]})
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [3]:
df.describe()

              A    B    C
count  2.000000  1.0  3.0
mean   1.500000  5.0  2.0
std    0.707107  NaN  1.0
min    1.000000  5.0  1.0
25%    1.250000  5.0  1.5
50%    1.500000  5.0  2.0
75%    1.750000  5.0  2.5
max    2.000000  5.0  3.0

In [4]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [5]:
df.isnull()

       A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [6]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [7]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [8]:
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [9]:
df.dropna(thresh=1)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [10]:
df.fillna(value=5)

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  5.0  5.0  3