<a href="https://colab.research.google.com/github/priyanshu742/PythonIntern/blob/main/NumpyPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd

In [9]:
import numpy as np

In [10]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={'a':10,'b':20,'c':30}

In [11]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [12]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [13]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [14]:
pd.Series(arr,index=["A","B","C"])

A    10
B    20
C    30
dtype: int64

In [15]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [16]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [17]:
s1=pd.Series([sum,print,len])
s1

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [18]:
s1[0]([1,2])

3

In [19]:
ser1=pd.Series(data=[1,2,3,4],index=['USA','Germany','USSR','Japan'])
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [20]:
ser2=pd.Series(data=[1,2,5,4],index=['USA','Germany','Italy','Japan'])
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [21]:
ser1['USA']

np.int64(1)

In [22]:
ser1+ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [23]:
ser1-ser2

Germany    0.0
Italy      NaN
Japan      0.0
USA        0.0
USSR       NaN
dtype: float64

In [24]:
ser1*2

USA        2
Germany    4
USSR       6
Japan      8
dtype: int64