<a href="https://colab.research.google.com/github/priyanshu742/PythonIntern/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:
from numpy.random import randn

In [5]:
np.random.seed(101)

In [6]:
df=pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [7]:
df[['Y','X']]

          Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
C  0.528813  0.740122
D -0.933237 -0.758872
E  2.605967  1.978757